### ISSUE TITLE
binary translation in softmmu mode

### ISSUE THREAD

**Issue by s0i37** [atos-tools/qemu-plugins-tutorial#2]
Hello.
I try to write test plugin or use icount in softmmu-mode, but I dont see anything in output.
I do so:
```
./x86_64-softmmu/qemu-system-x86_64 -hda ~/os/images/winXP.qcow2 --tcg-plugin icount -m 1G -monitor stdio
(qemu) stop
(qemu) loadvm some_state
(qemu) cont
```
May be I make something wrong?

**Comment by second-reality** [comment]
Moved issue here(main qemu repo): https://github.com/atos-tools/qemu/issues/2
